export const Posts = [
  {
    id: 1,
    description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    photo: 'assets/post/1.jpeg',
    date: '30 minutos atrás',
    userId: 1,
    like: 30,
    comment: 4
  },
  {
    id: 2,
    description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    photo: 'assets/post/2.jpeg',
    date: '1 minutos atrás',
    userId: 2,
    like: 3,
    comment: 0
  },
  {
    id: 3,
    description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    photo: 'assets/post/3.jpeg',
    date: '2 minutos atrás',
    userId: 3,
    like: 10,
    comment: 2
  },
  {
    id: 4,
    description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    photo: 'assets/post/4.jpeg',
    date: '15 minutos atrás',
    userId: 4,
    like: 4,
    comment: 1
  },
  {
    id: 5,
    description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    photo: 'assets/post/5.jpeg',
    date: '6 minutos atrás',
    userId: 5,
    like: 0,
    comment: 0
  },
  {
    id: 6,
    description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    photo: 'assets/post/6.jpeg',
    date: '6 minutos atrás',
    userId: 6,
    like: 6,
    comment: 6
  },
  {
    id: 7,
    description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    photo: 'assets/post/7.jpeg',
    date: '15 minutos atrás',
    userId: 7,
    like: 113,
    comment: 55
  },
  {
    id: 8,
    description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    photo: 'assets/post/8.jpeg',
    date: '5 minutos atrás',
    userId: 8,
    like: 0,
    comment: 0
  },
  {
    id: 9,
    description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    photo: 'assets/post/9.jpeg',
    date: '6 minutos atrás',
    userId: 9,
    like: 2,
    comment: 0
  },
  {
    id: 10,
    description: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...',
    photo: 'assets/post/10.jpeg',
    date: '16 minutos atrás',
    userId: 10,
    like: 3,
    comment: 0
  },
]

export const Users = [
  {
		"_id": 1,
		"userName": "Joyner",
		"email": "in.lobortis@outlook.org",
		"password": "EFU54YSY4PX",
		"profilePicture": "assets/person/1.jpeg",
		"coverPicture": 7892,
		"followers": "",
		"followings": 9,
		"isAdmin": false,
		"description": "tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget",
		"city": "Whitehorse",
		"from": "4097 Parturient Ave",
		"relationship": 2,
    "online": true
	},
	{
		"_id": 2,
		"userName": "Edwards",
		"email": "ornare.libero@protonmail.net",
		"password": "VCH26MPZ4IX",
		"profilePicture": "assets/person/2.jpeg",
		"coverPicture": 7590,
		"followers": "",
		"followings": 19,
		"isAdmin": false,
		"description": "Aenean sed pede nec ante blandit viverra. Donec tempus, lorem",
		"city": "Kharan",
		"from": "6431 Maecenas Av.",
		"relationship": 2,
    "online": false
	},
	{
		"_id": 3,
		"userName": "George",
		"email": "dolor.nulla.semper@outlook.ca",
		"password": "YXX64DTJ5YO",
		"profilePicture": "assets/person/3.jpeg",
		"coverPicture": 9796,
		"followers": "",
		"followings": 11,
		"isAdmin": false,
		"description": "semper pretium neque. Morbi quis urna. Nunc quis arcu vel",
		"city": "Multan",
		"from": "406-3878 At St.",
		"relationship": 2,
    "online": false
	},
	{
		"_id": 4,
		"userName": "Mcguire",
		"email": "tempor.diam.dictum@aol.net",
		"password": "LTQ38UNC0QT",
		"profilePicture": "assets/person/4.jpeg",
		"coverPicture": 3555,
		"followers": "",
		"followings": 17,
		"isAdmin": false,
		"description": "semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque",
		"city": "Hilo",
		"from": "Ap #103-3674 Vulputate, St.",
		"relationship": 2,
    "online": true
	},
	{
		"_id": 5,
		"userName": "Nguyen",
		"email": "est@icloud.com",
		"password": "OPC51DHI6RE",
		"profilePicture": "assets/person/5.jpeg",
		"coverPicture": 9311,
		"followers": "",
		"followings": 7,
		"isAdmin": false,
		"description": "nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis",
		"city": "Klagenfurt",
		"from": "Ap 272-9750 Curabitur Street",
		"relationship": 1,
    "online": false
	},
	{
		"_id": 6,
		"userName": "Meadows",
		"email": "lobortis.mauris@yahoo.org",
		"password": "JKK26SXP2PM",
		"profilePicture": "assets/person/6.jpeg",
		"coverPicture": 5213,
		"followers": "",
		"followings": 17,
		"isAdmin": false,
		"description": "ipsum primis in faucibus orci luctus et ultrices posuere cubilia",
		"city": "Norman Wells",
		"from": "311-3966 Vel Street",
		"relationship": 3,
    "online": true
	},
	{
		"_id": 7,
		"userName": "Warner",
		"email": "nisl.sem.consequat@google.ca",
		"password": "JRU11BBE2DB",
		"profilePicture": "assets/person/7.jpeg",
		"coverPicture": 9975,
		"followers": "",
		"followings": 1,
		"isAdmin": false,
		"description": "Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor",
		"city": "São Gonçalo",
		"from": "199-433 Sed St.",
		"relationship": 3,
    "online": false
	},
	{
		"_id": 8,
		"userName": "Hewitt",
		"email": "phasellus@google.edu",
		"password": "ZRK36NUP9QQ",
		"profilePicture": "assets/person/8.jpeg",
		"coverPicture": 9964,
		"followers": "",
		"followings": 1,
		"isAdmin": false,
		"description": "Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla",
		"city": "Stalowa Wola",
		"from": "Ap 787-3412 Hendrerit Street",
		"relationship": 2,
    "online": false
	},
	{
		"_id": 9,
		"userName": "Zimmerman",
		"email": "ut.nec@outlook.com",
		"password": "BOT72HOY1SO",
    "profilePicture": "assets/person/9.jpeg",
		"coverPicture": 6893,
		"followers": "",
		"followings": 15,
		"isAdmin": false,
		"description": "Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum.",
		"city": "Cổ Lễ",
		"from": "813 Nunc Rd.",
		"relationship": 3,
    "online": true
	},
	{
		"_id": 10,
		"userName": "Mejia",
		"email": "libero.proin.sed@outlook.ca",
		"password": "UMQ58EDF6OT",
		"profilePicture": "assets/person/10.jpeg",
		"coverPicture": 9113,
		"followers": "",
		"followings": 1,
		"isAdmin": false,
		"description": "eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce",
		"city": "Mexicali",
		"from": "Ap 405-5477 Lacinia. Avenue",
		"relationship": 1,
    "online": false
	}
]